<?php

function helloworld_menu() {
  $items = array();

  $items['helloworld'] = array(
    'title' => 'Hello World',
    'page callback' => 'helloworld_test',
    'page arguments' => array(),
     'access callback' => TRUE,
    //'access callback' => 'custom_user_access',
    //'access arguments' => array('access hello world'),
    'type' => MENU_NORMAL_ITEM,
  );

    $items['goodnightworld'] = array(
    'title' => 'Goodnight World',
    'page callback' => 'goodnight_world',
    'page arguments' => array(),
    'access callback' => TRUE,
    // 'access callback' => 'user_access',
    //'access arguments' => array('access goodnight world'),
    'type' => MENU_NORMAL_ITEM,
  );


  return $items;
}

function goodnight_world() {
   $form = drupal_get_form('user_perm_form');

   return $form;

}

function helloworld_test($name = NULL, $age = NULL) {
  $query = db_insert('helloworld_people')
  ->fields(array(
    'name'=> $name,
    'age'=> $age,
    ))
  ->execute();

  $time_string;

  while($age >=0) {
     $time_string .= $age . '<br>';
    $age--;
  }


  return $time_string . '<br>   Hello ' . $name;
}

function helloworld_permission() {
  $perms = array();

  $perms['access hello world'] = array(
    'title' => t('access hello world'),
    'description' => t('to access hello world'),

  );

  return $perms;

}

function goodnight_world_permission() {
  $perms = array();

  $perms['access goodnight world'] = array(
    'title' => t('access goodnight world'),
    'description' => t('to access goodnight world'),

  );

  return $perms;

}


function custom_user_access($string, $account = NULL) {
  global $user;

  if (!isset($account)) {
    $account = $user;
  }

  // User has all the privileges
  if ($account->uid == 1)
    return true;

  // $pin_val = user_perm_form();

  // if (($pin_val % 2) == 0)
    // return true;

  return false;


}



function user_perm_form($form, $form_state) {
  $form['name'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'Name',
    '#maxlength' => 20,
    '#required' => TRUE, //make this field required
  );

  $form['age'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'Age',
    '#size' => 3,
    '#maxlength' => 3,
    '#required' => TRUE, //make this field required
  );

  $form['submit_botton'] = array(
    '#type' => 'submit',
    '#value' => t('Click Here!'),


  );

  return $form;


}


function helloworld_node_view($node, $view_mode, $langcode) {

  $node->content['a'] = array(
    '#markup' => 'this is a hook',
    '#weight' => 10,
  );

return $node;
}

function user_perm_form_submit($form, &$form_state) {



  $form_state['redirect'] = array(
    'helloworld/' . $form_state['values']['name'] .'/' . $form_state['values']['age'],
    // array (
    //   'query' => array (
    //     'name' => $form_state['values']['name'],
    //     'age' => $form_state['values']['age'],
    //   ),

    // ),

  );

}
