<?php

function helloworld_menu() {
  $items = array();

  $items['helloworld'] = array(
    'title' => 'Hello World',
    'page callback' => 'helloworld_test',
    'page arguments' => array(),
    'access callback' => true,
    // 'access callback' => 'user_access',
    // 'access arguments' => array(),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function helloworld_test() {
  return 'Hello World';
}
